import frame.CoreApp;
import test.controller.WordGameController;
import test.service.ChineseWordGame;
import test.service.EnglishWordGame;
import test.service.IWordGame;

import java.util.Arrays;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        List<Class> classes = Arrays.asList(
                WordGameController.class,
                ChineseWordGame.class,
                EnglishWordGame.class,
                IWordGame.class
        );

        new CoreApp(classes).run();
    }
}
